[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "credit_card_fraud_detection_with_dagster.definitions"
code_location_name = "credit_card_fraud_detection_with_dagster"
